In [1]:
#1. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [2]:
import numpy as np
import pandas as pd

In [8]:
arr1=np.array([1,7,13,105])
print(arr1)
print(f"size of memory occupied by array is :{arr1.nbytes}")

[  1   7  13 105]
size of memory occupied by array is :32


In [10]:
#2.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays. 

In [9]:
#3. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives, 10 tens, 10 twentys and 10 fiftys.

In [15]:
arr4=np.zeros(10)
arr5=np.ones(10)
arr6=5*arr5
arr7=10*arr5
arr8=20*arr5
arr9=50*arr5
print(arr4)
print(arr5)
print(arr6)
print(arr7)
print(arr8)
print(arr9)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [ ]:
#4. Write a NumPy program to create an array of integers from 30 to 70.

In [18]:
arr8=np.arange(30,70)
print(arr8)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [ ]:
#5.Write a NumPy program to create an array of integers from 50 to 95.

In [19]:
arr9=np.arange(50,96)
print(arr9)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [ ]:
#6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [22]:
arr10=np.arange(20,81,2)
print(arr10)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [ ]:
#7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [25]:
arr11=np.arange(21,81,2)
print(arr11)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [ ]:
#8. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.

In [26]:
arr12=np.random.randint(10,40,15)
print(arr12)

[18 13 25 38 21 29 31 29 19 12 19 36 38 17 14]


In [ ]:
#11. Create any two arrays & perform various mathematical operations. i.e. Addition, Substraction, Multiplication, Divide.

In [30]:
arr13=np.array([5,1,9,6,7])
arr14=np.array([9,6,1,2,8])
print(f"Addition :{arr13+arr14}")
print(f"Substraction :{arr13-arr14}")
print(f"Multiplication :{arr13*arr14}")
print(f"Division :{arr13/arr14}")

Addition :[14  7 10  8 15]
Substraction :[-4 -5  8  4 -1]
Multiplication :[45  6  9 12 56]
Division :[0.55555556 0.16666667 9.         3.         0.875     ]


In [ ]:
#12. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [ ]:
import numpy as np

In [31]:
m = np.arange(10,22).reshape((3,4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
#13.Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [ ]:
import numpy as np

In [32]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#14.Write a NumPy program to find the number of rows and columns in a given     matrix.

In [ ]:
import numpy as np

In [34]:
m = np.arange(10,22).reshape((3, 4))
print("Matrix:")
print(m)

print("No.of rows and column:")
print(m.shape)

Matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
No.of rows and column:
(3, 4)


In [ ]:
#15.Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [35]:
import numpy as np

In [36]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
#16.Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

In [ ]:
import numpy as np

In [37]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.88644081 0.59809737 0.34697357]
  [0.7037515  0.64778287 0.84206571]
  [0.73118372 0.66806268 0.1799773 ]]

 [[0.68492385 0.53942727 0.01777446]
  [0.68372819 0.32677907 0.40832558]
  [0.21939471 0.88641473 0.38955921]]

 [[0.69008271 0.95106635 0.53447374]
  [0.8006147  0.78895823 0.0262793 ]
  [0.80328025 0.96072799 0.60579533]]]


In [38]:
#17.Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.

In [39]:
import numpy as np

In [40]:
x = np.random.random((2, 3, 4))
print(x)

[[[0.18504504 0.84418327 0.2433872  0.47435598]
  [0.05285175 0.72945821 0.31351153 0.9560567 ]
  [0.56182237 0.10193482 0.02314029 0.3913347 ]]

 [[0.30311907 0.92917982 0.72861413 0.61062531]
  [0.20689163 0.81496896 0.68444902 0.34832612]
  [0.86726454 0.93819558 0.1133571  0.10037461]]]


In [ ]:
#18.Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [ ]:
import numpy as np

In [41]:
l = [22.5, 12.4, 50, 60.33]
print("Original list:", l)
a = np.array(l)
print("One-Dimensional Numpy array:", a)

Original list: [22.5, 12.4, 50, 60.33]
One-Dimensional Numpy array: [22.5  12.4  50.   60.33]


In [ ]:
#19.Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [ ]:
import numpy as np

In [42]:
x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
#20.Write a NumPy program to create an array with values ranging from 12 to 38.

In [ ]:
import numpy as np

In [43]:
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [ ]:
#21.Write a NumPy program to reverse an array (the first element becomes the last).

In [ ]:
import numpy as np

In [44]:
arr = np.array([10, 20, 30, 40, 50])
print("Original Array: ", arr)

arr_reversed = np.flip(arr)
print("Reversed Array:", arr_reversed)

Original Array:  [10 20 30 40 50]
Reversed Array: [50 40 30 20 10]


In [ ]:
#22.Write a NumPy program to convert an data type into to a floating type.

In [ ]:
import numpy as np

In [45]:
a = [1, 2, 3, 4]

x = np.asfarray(a)
print("Array converted to afloat type:")
print(x)

Array converted to afloat type:
[1. 2. 3. 4.]


In [ ]:
#23.Write a NumPy program to convert a list array.

In [ ]:
import numpy as np

In [46]:
arr = np.array([1, 2, 3, 4, 5])
arr = list(arr)
print(arr)

[1, 2, 3, 4, 5]


In [ ]:
#24.Write a NumPy program to get the element-wise remainder of an array of division.

In [ ]:
import numpy as np

In [47]:
x = np.arange(9)

print("Original Array:")
print(x)

print("Element-wise remaider of division:")
print(np.remainder(x, 4))

Original Array:
[0 1 2 3 4 5 6 7 8]
Element-wise remaider of division:
[0 1 2 3 0 1 2 3 0]


In [ ]:
#10.Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [48]:
arr12=np.random.randint(50,90,20)
print(arr12)

[64 53 72 83 85 65 76 82 84 61 83 82 72 72 85 83 51 76 77 66]


In [ ]:
#9.Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [49]:
arr13=np.random.randint(30,50,10)
print(arr13)

[38 44 48 32 39 48 39 45 33 36]
